package Logic;

import AutoGeneratedClasses.BattleShipGame;

import java.io.Serializable;

public class TrackingBoard implements Serializable {
    private static final long serialVersionUID = 4L;
    private TrackingSquare[][] board;
    private int boardSize;

    public class TrackingSquare implements Serializable {
        private static final long serialVersionUID = 5L;
        private boolean HasAttacked;
        private boolean isOccupied;

        public TrackingSquare(){
        }

        public TrackingSquare(boolean i_IsOccupied, boolean i_HasAttacked) {
            isOccupied = i_IsOccupied;
            HasAttacked = i_HasAttacked;
        }

        public boolean GetHasAttacked() {
            return HasAttacked;
        }

        public void SetHasAttacked(boolean i_WasAttacked) {
            HasAttacked = i_WasAttacked;
        }

        public boolean GetIsOccupied() {
            return isOccupied;
        }

        public void SetIsOccupied(boolean i_IsOccupied) {
            isOccupied = i_IsOccupied;
        }
    }

    public void SetBoard(TrackingSquare[][] i_Board) {
        board = i_Board;
    }

    public TrackingSquare[][] GetBoard() {
        return board;
    }

    public void Initialize(BattleShipGame i_Game) {
        boardSize = i_Game.getBoardSize();
        board = new TrackingSquare[boardSize][boardSize];
        for (int i = 0; i < boardSize; i++)
            for (int j = 0; j < boardSize; j++)
                board[i][j] = new TrackingSquare(false, false);
    }
}
